### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by zhiqiang00** [GitEventhandler/GNNBC#1]
您好：
        我想问一下，通过torch_geometric 包下载的数据集直接报错为.pt格式，为什么会报错呢？而且我看直接下载的数据集里面并没有你在读取数据集里需要提取的数据，如下图：
![image](https://user-images.githubusercontent.com/47971137/188160242-20e2e28e-7293-4336-8c8b-e3a7500a64ba.png)
正常下载的cora等数据集也没有n这个属性，请问这个是怎么回事呢？方便的话，可以直接提供一下数据集吗？谢谢

**Comment by GitEventhandler** [comment]
请根据[Readme](https://github.com/GitEventhandler/GNNBC#dataset-source)下载和安装数据集。数据集是放在Release里的。
